### ISSUE TITLE
Hidden Multiplication on functions

### ISSUE THREAD

**Issue by mcreng** [danvim/ProcalParsing#12]
### Codes
1. `2sin(&pi/2)`
2. `2->$A: &pi/2->$B: $A sin($B) display`

### Parsing
1. `Error: Parsing failed: 'Current token does not support led parsing' @  position 1:2 (index 1), current lexeme is function(sin), previous was number(2), and remaining are [lparen((), constant(&pi), divide(/), number(2), rparen()), colon(:), END]`
2. `2->$A: &pi/2->$B: ($Asin) * ($B) display`

### Result
1. ` `
2. `0`, which should have been `2`

**Comment by danvim** [comment]
No. 1 is an unexpected error, but no. 2 is expected behavior, just use a space to separate the function and the variable to invoke a hidden multiplication or use an `*` instead.

Should be fixed in commit fa11ad146d88cf1e571ec3d4c8a06e92e5020c39

**Comment by danvim** [comment]
Should be fixed in commit 91f528742ee35b6234eb5d045fe3716cde4946db for real this time.
