### ISSUE TITLE
Hidden Multiplication on PowerNode

### ISSUE THREAD

**Issue by mcreng** [danvim/ProcalParsing#17]
The program ```2^(3)``` is parsed with error ```Current lexeme does not support nud parsing' @  position 1:3 (index 2), current lexeme is power(^), previous was multiply(*), and remaining are [lparen((), number(3), rparen()), colon(:), END]```.

**Comment by danvim** [comment]
Should be fixed in commit 516602a0c7a21575dec8e78736c52445934f85c6

**Comment by danvim** [comment]
Needs rebuilding

**Comment by mcreng** [comment]
Rebuilt in commit https://github.com/danvim/ProcalParsing/commit/d94de005695887b6ef70c3d6ecc4759a597c0a02.
