### ISSUE TITLE
Add Pol() and Rec() functions

### ISSUE THREAD

**Issue by danvim** [danvim/ProcalParsing#20]

**Comment by mcreng** [comment]
Note that `Pol(x, y)` and `Rec(r, theta)` stores something to the variable `$x` and `$y`.
I think for `Pol(x, y)`, `r -> $x` and `theta -> $y`
and for `Rec(r, theta)`,  `x -> $x` and `y -> $y`.
You might need to double check because I dont have the calculator with me as i type this.

**Comment by danvim** [comment]
@mcreng Yes, tested it. Will do.

**Comment by danvim** [comment]
Done in commit 79f78d57bf84e40ea93a26b3b9cd44b81e05456c
