### ISSUE TITLE
Revamp Hidden Multiplication: an attempt with nud/led instead of hardcode regex

### ISSUE THREAD

**Issue by bryanchun** [danvim/ProcalParsing#26]
Illustration of thought:

Each Node can specify whether it supports hidden multiplication or not in an attribute of the class.
Hence checking can be done by finding out whether there is some consecutive nodes both with this attribute.

For example, let say we have a boolean property `hiddenMultiplicative`
```
NumberNode.hiddenMultiplicative = true;
VariableNode.hiddenMultiplicative = true;
ConstantNode.hiddenMultiplicative = true;
AdditionNode.hiddenMultiplicative = false;
<NumberNode><VariableNode> // invokes Hidden multiplication
<VariableNode><VariableNode> // self-chain: invokes Hidden multiplication
<NumberNode><NumberNode> // commutative: invokes Hidden multiplication but shall this be banned?
<VariableNode><ConstantNode> // invokes Hidden multiplication
<NumberNode><AdditionNode> // Not invoked
```

**Comment by bryanchun** [comment]
Bug of this way:
```
2(3)/5
```
becomes 2*(3/5) not (2*3)/5
for 2/3(5) performs like (2/3)*5

**Comment by danvim** [comment]
This issue was closed because this suggestion does not work with the code structure and please refer to #1
