### ISSUE TITLE
Order of Operation

### ISSUE THREAD

**Issue by mcreng** [danvim/ProcalParsing#4]
### Codes
1. `5: 2->$A: $A Ans^5`
---
### Parsing
1. `5: 2->$A: ($A*Ans)^5`
---
### Results
1. `1024` //The problem seems to only affect Ans but not other var

**Comment by danvim** [comment]
All these are related to the operation of hidden multiplication.

I am going to remove hidden multiplication as `.led()`s in tokens and instead add `*` in places where multiplication is hidden before lexing by cleaning the input with regex.

**Comment by danvim** [comment]
Should be fixed in commit 7c636cadd07ad2fd35c32722fb7f5c2be30f5e9a

**Comment by danvim** [comment]
I forgot to remove the multiplication node at answer

**Comment by danvim** [comment]
Should be fixed in 4a35d5f172b06fed50a45237d648990a7c6c8e29
