### ISSUE TITLE
Statements

### ISSUE THREAD

**Issue by mcreng** [danvim/ProcalParsing#9]
### Codes
1. `If 1 Then 1 display IfEnd:`
2. `While 1: 1 display WhileEnd:`
3. `For 1->$A To 1: 1 display Next:`
---
### Returns
1. `Expected : but got IfEnd`
2. `Expected : but got WhileEnd`
3. `Expected : but got Next`

**Comment by danvim** [comment]
Don't know how this bug originates, but should be fixed in commit 64ab3c4ace7b91f58ea846a6e24fbd4e48862582

**Comment by danvim** [comment]
Can this issue be closed? Have you tested?
